name: APIM Proxygen Authentication

permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to authenticate against (e.g., dev, test, prod)'
        required: true
        type: string
      aws_region:
        description: 'AWS region for Secrets Manager'
        required: true
        type: string
      api_name:
        description: 'Name of the API to access via Proxygen'
        required: true
        type: string
    outputs:
      access_token:
        description: 'Short-lived access token for Proxygen API'
        value: ${{ jobs.get-access-token.outputs.token }}

jobs:
  get-access-token:
    name: Retrieve APIM Access Token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.access_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get APIM Access Token
        id: get-token
        uses: ./.github/actions/authenticate-apim
        with:
          api_name: ${{ inputs.api_name }}
          env: ${{ inputs.environment }}
          aws_region: ${{ inputs.aws_region }}
      - name: Test Token - List Proxy Instances
        env:
          ACCESS_TOKEN: ${{ steps.get-token.outputs.access_token }}
        run: |
          echo "Testing access token by hitting the API via APIM"

          curl --request GET \
          --url https://proxygen.prod.api.platform.nhs.uk/apis/dos-search \
          --header "Authorization: Bearer ::add-mask::$ACCESS_TOKEN"

      - name: Cleanup
        if: always()
        run: echo "âœ“ Cleanup completed"
