name: Prerelease Tag Automation

permissions:
  id-token: write
  contents: write

on:
  workflow_call:
    inputs:
      tag:
        description: "The Git tag to checkout"
        required: false
        type: string
    outputs:
      prerelease_tag:
        description: "The generated prerelease tag"
        value: ${{ jobs.generate-prerelease.outputs.prerelease_tag }}

jobs:
  generate-prerelease:
    name: "Generate prerelease tag"
    runs-on: ubuntu-latest
    outputs:
      prerelease_tag: ${{ steps.generate-prerelease.outputs.prerelease_tag }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.tag }}

      - name: "Generate prerelease tag"
        id: generate-prerelease
        uses: ./.github/actions/generate-prerelease
