name: Prerelease Tag Automation

permissions: {}

on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        required: false
        type: string
    outputs:
      prerelease_tag:
        description: "The generated prerelease tag"
        value: ${{ jobs.generate-prerelease.outputs.prerelease_tag }}

jobs:
  generate-prerelease:
    name: "Generate prerelease tag"
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    outputs:
      prerelease_tag: ${{ steps.generate-prerelease.outputs.prerelease_tag }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: "Generate prerelease tag"
        id: generate-prerelease
        uses: ./.github/actions/generate-prerelease
